version: '3'
services:
  axelor:
    image: axelor/aio-base
    build: .
    ports:
      - NGINX_PORT= ${DOMAIN_AXELOR}:443
    environment:
      - NGINX_HOST= ${DOMAIN_AXELOR}
      - NGINX_PORT= ${PORT_AXELOR}
    volumes:
#      - ./certs:/etc/nginx/certs:ro
      - ./volumes/var/lib/postgresql:/var/lib/postgresql
      - ./volumes/var/log/postgresql:/var/log/postgresql
      - ./volumes/var/lib/tomcat:/var/lib/tomcat
      - ./volumes/var/log/tomcat:/var/log/tomcat
