version: '3'
services:
  axelor:
    image: axelor/aio-erp
    build: .
    ports:
      - 8043:443
    environment:
#      - NGINX_HOST=localhost
#      - NGINX_PORT=443
      - VIRTUAL_HOST= ${DOMAIN_AXELOR}
      - LETSENCRYPT_HOST= ${DOMAIN_AXELOR}
      - LETSENCRYPT_EMAIL= ${LETSENCRYPT_EMAIL}      
    volumes:
#     - ./certs:/etc/nginx/certs:ro
      - ./volumes/var/lib/postgresql:/var/lib/postgresql
      - ./volumes/var/log/postgresql:/var/log/postgresql
      - ./volumes/var/lib/tomcat:/var/lib/tomcat
      - ./volumes/var/log/tomcat:/var/log/tomcat
      - ./application.properties:/application.properties

# Network name
# This container app must use a network conencted to the webproxy "evertramos"
# https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion

networks:
    default:
      external:
        name: webproxy
