version: '3'
services:
  axelor:
    image: axelor/aio-erp
    container_name: ${CONTAINER_AXELOR}
    ports:
      - ${PORT_AXELOR}:443
    environment:
      - VIRTUAL_HOST= ${DOMAIN_AXELOR}
      - LETSENCRYPT_HOST= ${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL= ${LETSENCRYPT_EMAIL}

# Network name
# This container app must use a network conencted to the webproxy "evertramos"
# https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion

networks:
    default:
      external:
        name: webproxy
